<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        //DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Âm Nhạc Lớp 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'an_6.png',
                'product_photo_path' => '/storage/product/1/iAfYSfY4n76ZevXMUqM8.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'ANL6',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:27:00',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Âm Nhạc Lớp 7',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'an_7.png',
                'product_photo_path' => '/storage/product/1/kGpt6r5PJXiWMNVlN40H.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'ANL7',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:27:40',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Âm Nhạc Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'an_8.png',
                'product_photo_path' => '/storage/product/1/tXLCISx0AIPewFZV7LZQ.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'ANL8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:04:06',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Âm Nhạc Lớp 9',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'an_9.png',
                'product_photo_path' => '/storage/product/1/MieJrKdRBEB3KydrpEwF.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'ANL9',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:04:11',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Công Nghệ Lớp 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_6.png',
                'product_photo_path' => '/storage/product/1/QOOrsw2cXBlj9AiQ5aLl.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL6',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:04:18',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Công Nghệ Lớp 7',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_7.png',
                'product_photo_path' => '/storage/product/1/fMX3HvfR2gkOheWGAJlZ.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL7',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:31:50',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Công Nghệ Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_8.png',
                'product_photo_path' => '/storage/product/1/ycwhsN35fRYwAbCaIQIL.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:32:18',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Công Nghệ Lớp 9 Định Hướng Nghề Nghiệp',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_9_dinh_huong_nghe_nghiep.png',
                'product_photo_path' => '/storage/product/1/TetLbzkYfGiTdQfV5lu3.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL9DHNN',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:32:37',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Công Nghệ Lớp 9 Lắp Đặt Mạng Điện Trong Nhà',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_9_lap_dat_mang_dien.png',
                'product_photo_path' => '/storage/product/1/rFSVWLatL4t6RQmKUQ5m.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL9LDDN',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:33:06',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Công Nghệ Lớp 9 Mô Đun Cắt May',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_9_mo_dun_cat_may.png',
                'product_photo_path' => '/storage/product/1/WesiWNGKUAZp94wy6u7i.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL9MDCM',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 09:33:35',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Công Nghệ Lớp 10 Thiết Kế Và Công Nghệ',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_10.png',
                'product_photo_path' => '/storage/product/1/hbTA42RV6RBX3mYRal2w.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL10TKCN',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:01:51',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Công Nghệ Lớp 10 Công Nghệ Trồng Trọt',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_10_cong_nghe_trong_trot.png',
                'product_photo_path' => '/storage/product/1/RIXL9NME5fJEVSbMT67N.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL10CNTT',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:02:26',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Công Nghệ Lớp 11 Công Nghệ Chăn Nuôi',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_11_cong_nghe_chan_nuoi.png',
                'product_photo_path' => '/storage/product/1/jsUqd7YgXb8cJUR9GBKE.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL11CNCN',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:02:51',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Công Nghệ Lớp 11 Công Nghệ Cơ Khí',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_11_cong_nghe_co_khi.png',
                'product_photo_path' => '/storage/product/1/4GNyFf4A3CO4nybdoJmu.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL10CNCK',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:03:15',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Công Nghệ Lớp 12 Lâm Nghiệp Thuỷ Sản',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cn_12_lam_nghiep_thuy_san.png',
                'product_photo_path' => '/storage/product/1/02nxyQOEBWbmqYqxjhak.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CNL10LNTS',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:03:33',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Lịch Sử Và Địa Lí Lớp 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lsvdl_6.png',
                'product_photo_path' => '/storage/product/1/Ou5PylK9aNNDzS6g1o4i.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSDLL6',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:15:21',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Lịch Sử Và Địa Lí Lớp 7',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lsvdl_7.png',
                'product_photo_path' => '/storage/product/1/I0gMGTeki0fAWCijvubm.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSDLL7',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:15:34',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Lịch Sử Và Địa Lí Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lsvdl_8.png',
                'product_photo_path' => '/storage/product/1/EMMdDBwk8oO516QzZfgq.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSDLL8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:15:45',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Lịch Sử Và Địa Lý Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lsvdl_8.png',
                'product_photo_path' => '',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => '',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:08:31',
                'deleted_at' => '2024-07-02 10:08:31',
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Lịch Sử Và Địa Lí Lớp 9',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lsvdl_9.png',
                'product_photo_path' => '/storage/product/1/b8Pv6kgT4hgBwsCmvMdk.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSDLL9',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:15:54',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Lịch Sử Lớp 10',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ls10.png',
                'product_photo_path' => '/storage/product/1/JLHyHVm8ThNDsOvzRNC7.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSL10',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:22:17',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Lịch Sử Lớp 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ls11.png',
                'product_photo_path' => '/storage/product/1/ZMXOALLARhXkOyh6Uh3I.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSL11',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 10:23:14',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Lịch Sử Lớp 12',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ls12.png',
                'product_photo_path' => '/storage/product/1/G2ZwBap9oM3wgwjz5kGY.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'LSLL12',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:09:18',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Địa Lí Lớp 10',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'dl_10.png',
                'product_photo_path' => '/storage/product/1/XTfrvlLsrvrxoIRT9992.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'DLL10',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:16:05',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Địa Lí Lớp 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'dl_11.png',
                'product_photo_path' => '/storage/product/1/c7eq0Ppr4aXokl6fDAg4.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'DLL11',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:16:20',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Địa Lí Lớp 12',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'dl_12.png',
                'product_photo_path' => '/storage/product/1/VN6IhA3YofgzqQ6yBAbn.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'DLL12',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:16:31',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Mĩ Thuật Lớp 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'mt_6.png',
                'product_photo_path' => '/storage/product/1/HqgGkZF24m5zrEzhmmBl.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'MTL6',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:17:27',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Mĩ Thuật Lớp 7',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'mt_7.png',
                'product_photo_path' => '/storage/product/1/ceUPkNujZzYQJkyVaWuY.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'MTL7',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:17:54',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Mĩ Thuật Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'mt_8.png',
                'product_photo_path' => '/storage/product/1/de8AzzlOTKpU7pYgKbsU.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'MTL8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:18:14',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Mĩ Thuật Lớp 9',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'mt_9.png',
                'product_photo_path' => '/storage/product/1/BacT39iY8VlRq76k1oRv.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'mTL9',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:18:37',
                'deleted_at' => NULL,
                'category_id' => 5,
                'publisher_id' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Ngữ Văn Lớp 6 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_6_1.png',
                'product_photo_path' => '/storage/product/1/qUvuzrQXMMbFr2GiGJ0c.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL6T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:19:11',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Ngữ Văn Lớp 6 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_6_2.png',
                'product_photo_path' => '/storage/product/1/dWCWIQ2EA3l5v9yhqLU2.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NGL6T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:20:09',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Ngữ Văn Lớp 7 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_7_1.png',
                'product_photo_path' => '/storage/product/1/bx9QVViMuad8YnCFDk3E.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL7T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:20:35',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Ngữ Văn Lớp 7 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_7_2.png',
                'product_photo_path' => '/storage/product/1/PXHJr7Lrt8YZxZF85xdV.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL7T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:21:24',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Ngữ Văn Lớp 8 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_8_1.png',
                'product_photo_path' => '/storage/product/1/PDDZRaWYbC3tOvkPQkV8.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL8T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:21:48',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Ngữ Văn Lớp 8 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_8_2.png',
                'product_photo_path' => '/storage/product/1/HTiHoX422QIRMhah3DL0.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL8T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:25:47',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Ngữ Văn Lớp 9 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_9_1.png',
                'product_photo_path' => '/storage/product/1/2vu7lCPcd4UzLaJXiVeN.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL9T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:27:51',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Ngữ Văn Lớp 9 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_9_2.png',
                'product_photo_path' => '/storage/product/1/9Fpg7JLa9Mc7NvjHTxTw.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL9T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:28:21',
                'deleted_at' => NULL,
                'category_id' => 10,
                'publisher_id' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Ngữ Văn Lớp 10 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_10_1.png',
                'product_photo_path' => '/storage/product/1/CbgAKD81HR0M6I2iXr5c.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL10T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:28:53',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Ngữ Văn Lớp 10 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_10_2.png',
                'product_photo_path' => '/storage/product/1/CTVi3YGEIvnCo5F8sGVA.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL10T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:29:21',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Ngữ Văn Lớp 11 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_11_1.png',
                'product_photo_path' => '/storage/product/1/yGuQrVsEeGIgLQqo9E5P.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL11T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:29:57',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Ngữ Văn Lớp 11 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_11_2.png',
                'product_photo_path' => '/storage/product/1/05kNagPxRQvrQEPlP7ii.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL11T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:31:15',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Ngữ Văn Lớp 12 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_12_1.png',
                'product_photo_path' => '/storage/product/1/roVgAIEi4ryNu7XQ8u8S.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL12T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:31:47',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Ngữ Văn Lớp 12 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngu_van_12_2.png',
                'product_photo_path' => '/storage/product/1/N1Iypn0QjT0aXcz8F8nJ.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'NVL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:32:23',
                'deleted_at' => NULL,
                'category_id' => 11,
                'publisher_id' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Toán Lớp 6 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_6_1.png',
                'product_photo_path' => '/storage/product/1/94c6TgglAW9dXNTfvYXh.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL6T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:42:18',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Toán Lớp 6 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_6_2.png',
                'product_photo_path' => '/storage/product/1/ybJ3C1Ey6u8uL7HVYWAA.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL6T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:43:38',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Toán Lớp 7 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_7_1.png',
                'product_photo_path' => '/storage/product/1/MfRZC95TxmhcZpRzsLHK.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL7T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:43:49',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Toán Lớp 7 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_7_2.png',
                'product_photo_path' => '/storage/product/1/NfIp3ofnOyrPppvZvFXL.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL7T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:44:10',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Toán Lớp 8 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_8_1.png',
                'product_photo_path' => '/storage/product/1/dtvRkpBeCEjba0r9xvJI.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL8T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:47:06',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Toán Lớp 8 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_8_2.png',
                'product_photo_path' => '/storage/product/1/k6wOJr6veXLzPMAbriCM.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL8T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:46:50',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Toán Lớp 9 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_9_1.png',
                'product_photo_path' => '/storage/product/1/089lAs1yTaLcweD0glKx.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL9T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:47:39',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Toán Lớp 9 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_9_2.png',
                'product_photo_path' => '/storage/product/1/XV4IxLo54pbaWXsVOUTe.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL9T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:48:08',
                'deleted_at' => NULL,
                'category_id' => 13,
                'publisher_id' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Toán Lớp 10 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_10_1.png',
                'product_photo_path' => '/storage/product/1/ekmSv9cvCHhvLWkBAd3u.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL10T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:48:35',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Toán Lớp 10 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_10_2.png',
                'product_photo_path' => '/storage/product/1/sAzmmrKf0a224zbd6ySA.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL10T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:49:58',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Toán Lớp 11 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_11_1.png',
                'product_photo_path' => '/storage/product/1/Q0if1w6Dt2Xk6RJQmJuM.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL11T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:50:27',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Toán Lớp 11 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_11_2.png',
                'product_photo_path' => '/storage/product/1/uzhfJzYTpPwPe84cIGMa.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL11T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:50:58',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Toán Lớp 12 Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_12_1.png',
                'product_photo_path' => '/storage/product/1/L46Tj8vq5pRJZ3tqa244.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'T12T1',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:52:07',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Toán Lớp 12 Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'toan_12_2.png',
                'product_photo_path' => '/storage/product/1/JtyNDzUi0wvJYueYmaw1.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:52:43',
                'deleted_at' => NULL,
                'category_id' => 14,
                'publisher_id' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Tiếng Anh Lớp 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_6.png',
                'product_photo_path' => '/storage/product/1/FiKaAwmPBXSzvnVkwdbA.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'tAL6',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:27:35',
                'deleted_at' => NULL,
                'category_id' => 16,
                'publisher_id' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Tiếng Anh Lớp 7',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_7.png',
                'product_photo_path' => '/storage/product/1/c1jtAvIlt74pWL82su95.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'tAL7',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:27:52',
                'deleted_at' => NULL,
                'category_id' => 16,
                'publisher_id' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Tiếng Anh Lớp 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_8.png',
                'product_photo_path' => '/storage/product/1/AUslxzp5OwKs8xDaMMbI.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'tAL8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:28:12',
                'deleted_at' => NULL,
                'category_id' => 16,
                'publisher_id' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Tiếng Anh Lớp 9',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_9.png',
                'product_photo_path' => '/storage/product/1/f8jTvKMJ2eTOGPXSpHjJ.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:18:54',
                'deleted_at' => NULL,
                'category_id' => 16,
                'publisher_id' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Tiếng Anh Lớp 10',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_10.png',
                'product_photo_path' => '/storage/product/1/qble8DBW3WKzeHIrtF5O.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:20:05',
                'deleted_at' => NULL,
                'category_id' => 17,
                'publisher_id' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Tiếng Anh Lớp 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_11.png',
                'product_photo_path' => '/storage/product/1/nkxJMLLNk3y2dqYVn7EP.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:20:13',
                'deleted_at' => NULL,
                'category_id' => 17,
                'publisher_id' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Tiếng Anh Lớp 12',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ta_12.png',
                'product_photo_path' => '/storage/product/1/v1HQ0UCObawCa17KLUdB.png',
                'regular_price' => 27000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'TL12T2',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 21:20:20',
                'deleted_at' => NULL,
                'category_id' => 17,
                'publisher_id' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => '100 Đề Kiểm Tra Toán 8',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => '100kt-t8.jpg',
                'product_photo_path' => '/storage/product/1/c5VxMjN7oxqpacxcF5KD.jpg',
                'regular_price' => 80000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => '100DKTT8',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:53:18',
                'deleted_at' => NULL,
                'category_id' => 19,
                'publisher_id' => 4,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => '50 Đề Minh Họa 2023 Môn Toán Học',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => '50dmh-t12.jpg',
                'product_photo_path' => '/storage/product/1/XhdPDHEkhsxVw7zUIBB0.jpg',
                'regular_price' => 180000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'nhiều tác giả',
                'code' => '50DMHMTH',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:55:54',
                'deleted_at' => NULL,
                'category_id' => 19,
                'publisher_id' => 7,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Chinh Phục Luyện Thi Vào Lớp 10 Môn Toán Theo Chủ Đề',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'cp-ltl10-t9.jpg',
                'product_photo_path' => '/storage/product/1/GB59HNhIJh0CMipFZ923.jpg',
                'regular_price' => 180000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nguyễn Xuân Nam',
                'code' => 'CPLTVL10MTTCD',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 13:57:03',
                'deleted_at' => NULL,
                'category_id' => 19,
                'publisher_id' => 8,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Phương Pháp Giải Các Chuyên Đề Căn Bản Đại Số Giải Tích 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ppg-ds11.jpg',
                'product_photo_path' => '/storage/product/1/YhhM3DWcSOFnI7GDtXik.jpg',
                'regular_price' => 97000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Lê Hoành Phò',
                'code' => 'PPGCCDCBDSGT11',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:01:05',
                'deleted_at' => NULL,
                'category_id' => 19,
                'publisher_id' => 8,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Phương Pháp Giải Toán Chuyên Đề Giải Tích 12',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ppg-ds12.jpg',
                'product_photo_path' => '/storage/product/1/vmq9Reb9RGmgEpMEgAph.jpg',
                'regular_price' => 114000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'nhiều tác giả',
                'code' => 'PPGTCDGT12',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:02:44',
                'deleted_at' => NULL,
                'category_id' => 19,
                'publisher_id' => 8,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Luyện Giải Bộ Đề Bồi Dưỡng Học Sinh Giỏi Tiếng Anh Lớp 10',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lgbdbdhsgta10.png',
                'product_photo_path' => '/storage/product/1/djx5rBd2pp79HEvPY35v.png',
                'regular_price' => 90000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Dương Hương',
                'code' => 'lGBDBDHSGTAL10',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:15:35',
                'deleted_at' => NULL,
                'category_id' => 21,
                'publisher_id' => 8,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Luyện Giải Bộ Đề Bồi Dưỡng Học Sinh Giỏi Tiếng Anh Lớp 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lcsnp_ta11.png',
                'product_photo_path' => '/storage/product/1/pbVGW1beBFCvjjqvSIUZ.png',
                'regular_price' => 90000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Dương Hương',
                'code' => 'lGBDBDHSGTAL11',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:08:48',
                'deleted_at' => NULL,
                'category_id' => 21,
                'publisher_id' => 8,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Luyện Giải Bộ Đề Bồi Dưỡng Học Sinh Giỏi Tiếng Anh Lớp 12',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lcsnp_ta12.png',
                'product_photo_path' => '/storage/product/1/1rHTIGLtncm8JetzAIq2.png',
                'regular_price' => 90000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Dương Hương',
                'code' => 'lGBDBDHSGTAL12',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:09:37',
                'deleted_at' => NULL,
                'category_id' => 21,
                'publisher_id' => 8,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Luyện Chuyên Sâu Ngữ Pháp Và Bài Tập Tiếng Anh Lớp 10',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lcsnp_ta10.png',
                'product_photo_path' => '/storage/product/1/2K0zmauZdFEsEtUd4e7o.png',
                'regular_price' => 89000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Dương Hương',
                'code' => 'LCSNPVBTTAL10',
                'publishing_year' => '2017',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:10:22',
                'deleted_at' => NULL,
                'category_id' => 21,
                'publisher_id' => 8,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Học Tốt Tiếng Anh 11 Theo Chương Trình Global Success',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'htta11.png',
                'product_photo_path' => '/storage/product/1/D5asIn00WtMp4eE8FVZN.png',
                'regular_price' => 145000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'nhiều tác giả',
                'code' => 'HTTA11',
                'publishing_year' => '2017',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:16:34',
                'deleted_at' => NULL,
                'category_id' => 21,
                'publisher_id' => 14,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Chuyên Đề Chuyên Sâu Bồi Dưỡng Ngữ Văn 11',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'chuyen_de_chuyen_sau_boi_duong_ngu_van_11.png',
                'product_photo_path' => '/storage/product/1/CPrxHl7kNRRh2oEj76DP.png',
                'regular_price' => 75000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'CDCSBDNV',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:17:11',
                'deleted_at' => NULL,
                'category_id' => 20,
                'publisher_id' => 14,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Hướng Dẫn Ôn Thi Tốt Nghiệp Trung Học Phổ Thông Môn Ngữ Văn',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'huong_dan_on_thi_tot_nghiep_trung_hoc_pho_thong_mon_ngu_van.png',
                'product_photo_path' => '/storage/product/1/NqeZzIbPEIWTRlqBEnMI.png',
                'regular_price' => 65000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'HDOTTNTHPTMNV',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:19:13',
                'deleted_at' => NULL,
                'category_id' => 20,
                'publisher_id' => 1,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Ôn Luyện Thi Tốt Nghiệp THPT Năm 2024 Môn Ngữ Văn',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'on_luyen_thi_tot_nghiep_thpt_nam_2024_mon_ngu_van.png',
                'product_photo_path' => '/storage/product/1/K7wUrD6SSGmGqoVeKClz.png',
                'regular_price' => 65000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'OLTTNTHPTN2024MNV',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:19:57',
                'deleted_at' => NULL,
                'category_id' => 20,
                'publisher_id' => 8,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => '25 Đề Tự Ôn Luyện Thi THPT Quốc Gia Môn Ngữ Văn',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => '25_de_tu_on_luyen_thi_thpt_quoc_gia_mon_ngu_van.png',
                'product_photo_path' => '/storage/product/1/nouggHH45yQ38thGpPcr.png',
                'regular_price' => 70000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => '25DTOLTTHPTQGMNV',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:20:47',
                'deleted_at' => NULL,
                'category_id' => 20,
                'publisher_id' => 14,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => '100 Kỹ Năng Sinh Tồn',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => '100_ki_nang_sinh_ton.png',
                'product_photo_path' => '/storage/product/1/SP90ZKtv8IZfbMHEgujb.png',
                'regular_price' => 99000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Clint Emerson',
                'code' => '100KNST',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:21:12',
                'deleted_at' => NULL,
                'category_id' => 25,
                'publisher_id' => 7,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Who Chuyện Kể Về Danh Nhân Thế Giới Elon Musk',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'whoelonmusk.png',
                'product_photo_path' => '/storage/product/1/JJCZwMReOZt0y8C7BECE.png',
                'regular_price' => 60000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'WKVDNTGEM',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:24:09',
                'deleted_at' => NULL,
                'category_id' => 25,
                'publisher_id' => 3,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Geography Encyclopedia Bách Khoa Toàn Thư Về Địa Lý',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'bach_khoa_toan_thu_dia_ly.png',
                'product_photo_path' => '/storage/product/1/WFm7B35HBzFcQDwmLvuw.png',
                'regular_price' => 289000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'GEBKTTVDL',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:25:43',
                'deleted_at' => NULL,
                'category_id' => 25,
                'publisher_id' => 7,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Who Chuyện Kể Về Danh Nhân Thế Giới Bill Gates',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'whobillgate.png',
                'product_photo_path' => '/storage/product/1/qrPRRNJtUzXbTp0q86jJ.png',
                'regular_price' => 60000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'WKVDNTGBG',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:28:30',
                'deleted_at' => NULL,
                'category_id' => 25,
                'publisher_id' => 3,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Bách Khoa Tri Thức Về Khám Phá Thế Giới Cho Trẻ Em Khủng Long',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'bach_khoa_toan_thu_khung_long.png',
                'product_photo_path' => '/storage/product/1/7EpSwde9avhyxHeqxTjR.png',
                'regular_price' => 45000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'BKTTVKPTGCTEKL',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:29:24',
                'deleted_at' => NULL,
                'category_id' => 25,
                'publisher_id' => 12,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Doraemon Chú Mèo Máy Đến Từ Tương Lai Tập 1',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'doraemon_1.png',
                'product_photo_path' => '/storage/product/1/0wJCkT2G3q6NqqXJHQC4.png',
                'regular_price' => 22000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Fujiko F Fujio',
                'code' => 'DORAEMON1',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:30:36',
                'deleted_at' => NULL,
                'category_id' => 24,
                'publisher_id' => 3,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Doraemon Chú Mèo Máy Đến Từ Tương Lai Tập 2',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'doraemon_2.png',
                'product_photo_path' => '/storage/product/1/K2oWRrerkSjz4SCFUtYw.png',
                'regular_price' => 22000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Fujiko F Fujio',
                'code' => 'DORAEMON2',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:31:08',
                'deleted_at' => NULL,
                'category_id' => 24,
                'publisher_id' => 3,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Doraemon Chú Mèo Máy Đến Từ Tương Lai Tập 3',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'doraemon_3.png',
                'product_photo_path' => '/storage/product/1/I43TzmEoVQnyxKrMGtGv.png',
                'regular_price' => 22000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Fujiko F Fujio',
                'code' => 'DORAEMON3',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:31:33',
                'deleted_at' => NULL,
                'category_id' => 24,
                'publisher_id' => 3,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Doraemon Chú Mèo Máy Đến Từ Tương Lai Tập 4',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'doraemon_4.png',
                'product_photo_path' => '/storage/product/1/f2KVRXuVofFdwjxFMAl8.png',
                'regular_price' => 22000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Fujiko F Fujio',
                'code' => 'DORAEMON4',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:32:11',
                'deleted_at' => NULL,
                'category_id' => 24,
                'publisher_id' => 3,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Doraemon Chú Mèo Máy Đến Từ Tương Lai Tập 5',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'doraemon_5.png',
                'product_photo_path' => '/storage/product/1/6gkvaRrFB87BtYxEe0P5.png',
                'regular_price' => 22000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Fujiko F Fujio',
                'code' => 'DORAEMON5',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:32:42',
                'deleted_at' => NULL,
                'category_id' => 24,
                'publisher_id' => 3,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Hoàng Tử Bé',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'hoang_tu_be.png',
                'product_photo_path' => '/storage/product/1/uYscAf57nxBfdNsaxBbp.png',
                'regular_price' => 35000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Antoine De Saint Exupery',
                'code' => 'HTB',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:33:34',
                'deleted_at' => NULL,
                'category_id' => 23,
                'publisher_id' => 3,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'EQ IQ Giúp Trẻ Làm Chủ Cảm Xúc Cáu Giận',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'eq_iq_giup_tre_lam_chu_cam_xuc.png',
                'product_photo_path' => '/storage/product/1/S9AfB5unNGCCd4VAVMtI.png',
                'regular_price' => 35000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'nhiều tác giả',
                'code' => 'EIGTLCCXCG',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:34:36',
                'deleted_at' => NULL,
                'category_id' => 23,
                'publisher_id' => 7,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Bé Tập Kể Chuyện - Ba Người Bạn',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ba_nguoi_ban.png',
                'product_photo_path' => '/storage/product/1/GSTIZI1Q0PHwn9LzWoJG.png',
                'regular_price' => 15000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nhiều Tác Giả',
                'code' => 'BTKCBNB',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:34:59',
                'deleted_at' => NULL,
                'category_id' => 23,
                'publisher_id' => 2,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Những Lời Yêu Thương Của Con Trẻ Dành Tặng Các Mẹ Vì Sao Tớ Yêu Mẹ',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'vi_sao_to_yeu_me.png',
                'product_photo_path' => '/storage/product/1/2j9Gn7k6RwCbvGEUvgkx.png',
                'regular_price' => 25000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Daniel Howarth',
                'code' => 'NLYTCCDTCMVSTYM',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:36:11',
                'deleted_at' => NULL,
                'category_id' => 23,
                'publisher_id' => 3,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Ehon Kĩ Năng Sống Tập 6 Miu Bé Nhỏ Đừng Xem Tivi Nhiều Nhé Dành Cho Độ Tuổi Từ 1 đến 6',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'dung_xem_ti_vi_nhieu_nhe.png',
                'product_photo_path' => '/storage/product/1/BYu6vjJhgdtsBENwzhLj.png',
                'regular_price' => 39000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'nhiều tác giả',
                'code' => 'EKNST6MBNDXTNNDCDTT1D6',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:40:55',
                'deleted_at' => NULL,
                'category_id' => 23,
                'publisher_id' => 13,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Một Thoáng Ta Rực Rỡ Ở Nhân Gian',
                'description' => 'Mô tả',
                'content' => 'Một Thoáng Ta Rực Rỡ Ở Nhân Gian

“Vuong thực sự có thiên tài quan sát.” The New York Times

“Với một xuất thân bên rìa hết sức xa lạ, Vuong đã viết nên một tác phẩm trữ tình về quá trình tự khám phá chính mình, vừa thành thật đến choáng váng, vừa phổ quát trong từng câu chữ.” The Washington Post

“Bằng sự chính xác của một nhà thơ, Ocean Vuong xem xét liệu biến kinh nghiệm của chúng ta thành từ ngữ có thể chữa lành những vết thương trải hàng thế hệ hay không, và liệu tiếng nói của ta có thể nào thực sự được nghe bởi những người ta yêu thương nhất.” Celeste Ng

Một thoáng ta rực rỡ ở nhân gian viết dưới dạng một lá thư của nhân vật chính, Chó Con, gửi cho người mẹ không biết chữ của mình. Dưới dạng những mẩu chuyện nhỏ, xen kẽ với những đoạn trữ tình ngoại đề, triết lý, và những bài thơ, cuốn sách kể câu chuyện đời không chỉ của Chó Con (tên gọi yêu do bà ngoại đặt cho, nhưng cũng là cách tất cả mọi người trong sách gọi cậu) từ thuở nhỏ đến lúc chớm trưởng thành, mà cả ba thế hệ từ bà, đến mẹ, đến cậu, một cuộc di cư dài từ làng quê Việt Nam sang đất Mỹ, cũng như câu chuyện của những thanh niên Mỹ thế hệ cậu mà đặc trưng là người bạn trai Trevor.

Cuốn sách thường được đọc như một Bildungsroman (tiểu thuyết trưởng thành), nhưng cũng có nhiều người coi đây là một Künstlerroman (tiểu thuyết kể về quá trình một người nghệ sĩ trở thành nghệ sĩ).',
                'product_photo_name' => 'mttrrong.png',
                'product_photo_path' => '/storage/product/1/6Z1SZNsXffL3crk3uNZ3.png',
                'regular_price' => 135000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Ocean Vương',
                'code' => 'MTTRRONG',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:41:33',
                'deleted_at' => NULL,
                'category_id' => 3,
                'publisher_id' => 6,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Tắt Đèn Ngô Tất Tố',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'tat_den.png',
                'product_photo_path' => '/storage/product/1/3aDdC5KpggbpPDqX0gnV.png',
                'regular_price' => 86000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Ngô Tất Tố',
                'code' => 'tD_NTT',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:42:54',
                'deleted_at' => NULL,
                'category_id' => 3,
                'publisher_id' => 10,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Cho Tôi Xin Một Vé Đi Tuổi Thơ tái Bản 2023',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ctxmvvtt.png',
                'product_photo_path' => '',
                'regular_price' => 90000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'CTXMVDTTTB2023',
                'publishing_year' => '2023',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:44:38',
                'deleted_at' => NULL,
                'category_id' => 3,
                'publisher_id' => 2,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Mắt Biếc Tái Bản 2022',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'mat_biec.png',
                'product_photo_path' => '/storage/product/1/EASoen8fY8xycK7xo17I.png',
                'regular_price' => 43000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'MBTB2022',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:45:14',
                'deleted_at' => NULL,
                'category_id' => 3,
                'publisher_id' => 2,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Còn Chút Gì Để Nhớ Tái Bản 2022',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'conchutgidenho.png',
                'product_photo_path' => '/storage/product/1/xlFnVwkyBCPbesXHE4jZ.png',
                'regular_price' => 43000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'CCGDNTB2022',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:46:30',
                'deleted_at' => NULL,
                'category_id' => 3,
                'publisher_id' => 2,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Cây Cam Ngọt Của Tôi',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ccnct.png',
                'product_photo_path' => '/storage/product/1/agg5APkjEIBSQQPZ5pEq.png',
                'regular_price' => 100000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'José Mauro de Vasconcelos',
                'code' => 'CCNCT',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 17:00:50',
                'deleted_at' => NULL,
                'category_id' => 4,
                'publisher_id' => 6,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Nhà Giả Kim',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'ngk.png',
                'product_photo_path' => '/storage/product/1/xWoMChSP4npI28OEAfLs.png',
                'regular_price' => 79000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Paulo Coelho',
                'code' => 'NGK',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 17:01:02',
                'deleted_at' => NULL,
                'category_id' => 4,
                'publisher_id' => 6,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Kafka Bên Bờ Biển',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'kafka_ben_bo_bien.png',
                'product_photo_path' => '/storage/product/1/wJnBQahNMfxZiMSGihbq.png',
                'regular_price' => 150000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Haruki Murakami',
                'code' => 'KBBB',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:47:12',
                'deleted_at' => NULL,
                'category_id' => 4,
                'publisher_id' => 10,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Thép Đã Tôi Thế Đấy',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'thep_da_toi_the_day.png',
                'product_photo_path' => '/storage/product/1/0yCgRnXr1rrAhDk1NCuC.png',
                'regular_price' => 165000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Nikolai A Ostrovsky',
                'code' => 'TDTTD',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:47:39',
                'deleted_at' => NULL,
                'category_id' => 4,
                'publisher_id' => 10,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Lolita',
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'lolita.png',
                'product_photo_path' => '/storage/product/1/vXSUZMGP3PPWt6gPdRwI.png',
                'regular_price' => 120000.0,
                'sale_price' => 0.0,
                'discount' => 0,
                'author' => 'Vladimir Nabokov',
                'code' => 'LOLITA',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 0,
                'created_at' => '2024-07-02 09:27:00',
                'updated_at' => '2024-07-02 14:48:33',
                'deleted_at' => NULL,
                'category_id' => 4,
                'publisher_id' => 6,
            ),
        ));

    }
}