<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'asdasasdasdaad',
                'category_id' => 1,
                'description' => 'asdas',
                'content' => 'dasda',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product//d1eUb7SfSMJxZCsPhT1v.jpg',
                'regular_price' => 2312.0,
                'sale_price' => 21312.0,
                'discount' => '12',
                'publisher_id' => 2,
                'author' => 'dasda',
                'code' => 'sadas',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 17:42:37',
                'updated_at' => '2024-04-20 17:48:47',
                'deleted_at' => '2024-04-20 17:48:47',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Thương Nhớ Trà Long 2',
                'category_id' => 12,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product//al7SMow5EALOTrJeKJKd.jpg',
                'regular_price' => 120000.0,
                'sale_price' => 9000.0,
                'discount' => '10',
                'publisher_id' => 1,
                'author' => 'nguyen nhat anh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 17:46:43',
                'updated_at' => '2024-05-14 18:41:30',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Dark Nhân Tâm',
                'category_id' => 2,
                'description' => 'dasd',
                'content' => 'dasd',
                'product_photo_name' => 'prod2.jpg',
                'product_photo_path' => '/storage/product/1/bvjaBMHDKTWTi6pbvw06.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 2000.0,
                'discount' => '80',
                'publisher_id' => 1,
                'author' => 'nguyen nhat anh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 17:47:56',
                'updated_at' => '2024-05-14 18:40:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'cuốn sách đầu tiên',
                'category_id' => 12,
            'description' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>',
            'content' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product/1/dTBb8WNnsEsomdcL4Gip.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 10000.0,
                'discount' => '10',
                'publisher_id' => 1,
                'author' => 'Nguyễn nhật ánh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-21 15:33:00',
                'updated_at' => '2024-05-14 18:41:59',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'sadasdsadasdasda',
                'category_id' => 2,
                'description' => 'sadas',
                'content' => 'asdas',
                'product_photo_name' => NULL,
                'product_photo_path' => NULL,
                'regular_price' => 231.0,
                'sale_price' => 213.0,
                'discount' => '23',
                'publisher_id' => 1,
                'author' => '321',
                'code' => 'TNTL2024',
                'publishing_year' => '23',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-21 16:51:19',
                'updated_at' => '2024-04-21 16:54:38',
                'deleted_at' => '2024-04-21 16:54:38',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Cây Cam Ngọt Của Tôi',
                'category_id' => 2,
            'description' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span>',
            'content' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span>',
                'product_photo_name' => 'image_217480.jpg',
                'product_photo_path' => '/storage/product/1/jj7ibkKZUuhgvCDC8vvy.jpg',
                'regular_price' => 100000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 1,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'PRODUCTCODEX',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-28 15:00:28',
                'updated_at' => '2024-05-14 18:40:27',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
            'name' => 'Nhà Giả Kim (Tái Bản 2020)',
                'category_id' => 2,
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                'product_photo_name' => 'prod3.jpg',
                'product_photo_path' => '/storage/product/1/zbjceWG3Hb7bu3BwCtzD.jpg',
                'regular_price' => 1200000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 2,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'PRODUCTCODEX',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-28 15:01:47',
                'updated_at' => '2024-05-14 18:40:21',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 14,
                'name' => 'Cuốn sách thứ 2',
                'category_id' => 2,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod3.jpg',
                'product_photo_path' => '/storage/product/1/KwsOgAzcjLcGo3SPqSEU.jpg',
                'regular_price' => 100000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 2,
                'author' => 'Ba rọi béo',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-29 16:45:02',
                'updated_at' => '2024-05-14 18:40:17',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'Sản phẩm test 1',
                'category_id' => 2,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod3 - Copy.jpg',
                'product_photo_path' => '/storage/product/1/TBbGvCwGM0FWY6UvFNoe.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 10000.0,
                'discount' => '0',
                'publisher_id' => 1,
                'author' => 'Ba rọi béo',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-05-04 16:08:43',
                'updated_at' => '2024-05-08 18:41:04',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 20,
                'name' => 'asdasasdasdaad',
                'category_id' => 1,
                'description' => 'asdas',
                'content' => 'dasda',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product//d1eUb7SfSMJxZCsPhT1v.jpg',
                'regular_price' => 2312.0,
                'sale_price' => 21312.0,
                'discount' => '12',
                'publisher_id' => 2,
                'author' => 'dasda',
                'code' => 'sadas',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 10:42:37',
                'updated_at' => '2024-04-20 10:48:47',
                'deleted_at' => '2024-04-20 10:48:47',
            ),
            10 => 
            array (
                'id' => 21,
                'name' => 'Thương Nhớ Trà Long 2',
                'category_id' => 12,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product//al7SMow5EALOTrJeKJKd.jpg',
                'regular_price' => 120000.0,
                'sale_price' => 9000.0,
                'discount' => '10',
                'publisher_id' => 1,
                'author' => 'nguyen nhat anh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 10:46:43',
                'updated_at' => '2024-05-14 18:42:22',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 22,
                'name' => 'Dark Nhân Tâm',
                'category_id' => 12,
                'description' => 'dasd',
                'content' => 'dasd',
                'product_photo_name' => 'prod2.jpg',
                'product_photo_path' => '/storage/product/1/bvjaBMHDKTWTi6pbvw06.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 2000.0,
                'discount' => '80',
                'publisher_id' => 1,
                'author' => 'nguyen nhat anh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-20 10:47:56',
                'updated_at' => '2024-05-14 18:42:14',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 23,
                'name' => 'cuốn sách đầu tiên',
                'category_id' => 12,
            'description' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>',
            'content' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>',
                'product_photo_name' => 'prod1.jpg',
                'product_photo_path' => '/storage/product/1/dTBb8WNnsEsomdcL4Gip.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 10000.0,
                'discount' => '10',
                'publisher_id' => 1,
                'author' => 'Nguyễn nhật ánh',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-21 08:33:00',
                'updated_at' => '2024-05-14 18:42:06',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 24,
                'name' => 'sadasdsadasdasda',
                'category_id' => 2,
                'description' => 'sadas',
                'content' => 'asdas',
                'product_photo_name' => NULL,
                'product_photo_path' => NULL,
                'regular_price' => 231.0,
                'sale_price' => 213.0,
                'discount' => '23',
                'publisher_id' => 1,
                'author' => '321',
                'code' => 'TNTL2024',
                'publishing_year' => '23',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-21 09:51:19',
                'updated_at' => '2024-04-21 09:54:38',
                'deleted_at' => '2024-04-21 09:54:38',
            ),
            14 => 
            array (
                'id' => 25,
                'name' => 'Cây Cam Ngọt Của Tôi',
                'category_id' => 12,
            'description' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span>',
            'content' => '<strong style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;">Lorem Ipsum</strong><span style="color: rgb(0, 0, 0); font-family: "Open Sans", Arial, sans-serif; text-align: justify;"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span>',
                'product_photo_name' => 'image_217480.jpg',
                'product_photo_path' => '/storage/product/1/jj7ibkKZUuhgvCDC8vvy.jpg',
                'regular_price' => 100000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 1,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'PRODUCTCODEX',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-28 08:00:28',
                'updated_at' => '2024-05-14 18:41:52',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 26,
            'name' => 'Nhà Giả Kim (Tái Bản 2020)',
                'category_id' => 12,
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                'product_photo_name' => 'prod3.jpg',
                'product_photo_path' => '/storage/product/1/zbjceWG3Hb7bu3BwCtzD.jpg',
                'regular_price' => 1200000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 2,
                'author' => 'Nguyễn Nhật Ánh',
                'code' => 'PRODUCTCODEX',
                'publishing_year' => '2022',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-28 08:01:47',
                'updated_at' => '2024-05-14 18:41:39',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 27,
                'name' => 'Cuốn sách thứ 2',
                'category_id' => 2,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod3.jpg',
                'product_photo_path' => '/storage/product/1/KwsOgAzcjLcGo3SPqSEU.jpg',
                'regular_price' => 100000.0,
                'sale_price' => 70000.0,
                'discount' => '30',
                'publisher_id' => 2,
                'author' => 'Ba rọi béo',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-04-29 09:45:02',
                'updated_at' => '2024-05-10 19:45:25',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 28,
                'name' => 'Sản phẩm test 1',
                'category_id' => 2,
                'description' => 'Mô tả',
                'content' => 'Nội dung',
                'product_photo_name' => 'prod3 - Copy.jpg',
                'product_photo_path' => '/storage/product/1/TBbGvCwGM0FWY6UvFNoe.jpg',
                'regular_price' => 10000.0,
                'sale_price' => 10000.0,
                'discount' => '0',
                'publisher_id' => 1,
                'author' => 'Ba rọi béo',
                'code' => 'TNTL2024',
                'publishing_year' => '2020',
                'status' => 1,
                'outstanding' => 1,
                'created_at' => '2024-05-04 09:08:43',
                'updated_at' => '2024-05-10 19:45:20',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}